 Tue, 10 Mar 2020 15:15:33  INFO test_login.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Tue, 10 Mar 2020 15:15:34  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 15:15:34  INFO test_login.py test_login [ line:77 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 15:15:34  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '150 71369970', 'pwd': '123456'}
 Tue, 10 Mar 2020 15:15:34  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 15:15:35  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '18311252547', 'pwd': '1234568'}
 Tue, 10 Mar 2020 15:15:35  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 15:15:35  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '', 'pwd': '1234568'}
 Tue, 10 Mar 2020 15:15:35  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 15:15:36  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': ''}
 Tue, 10 Mar 2020 15:15:36  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'},测试通过
 Tue, 10 Mar 2020 15:15:36  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234569'}
 Tue, 10 Mar 2020 15:15:36  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 15:15:37  INFO test_login.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
 Tue, 10 Mar 2020 15:15:37  INFO test_recharge.py setUpClass [ line:41 ] ==================== 准备开始执行充值接口测试 ====================
 Tue, 10 Mar 2020 15:15:37  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 15:15:37  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 15:15:37  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '200'}
 Tue, 10 Mar 2020 15:15:38  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '7786.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'}, 实际结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '7786.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'},测试通过
 Tue, 10 Mar 2020 15:15:38  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13296147453', 'amount': '200'}
 Tue, 10 Mar 2020 15:15:38  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'}, 实际结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'},测试通过
 Tue, 10 Mar 2020 15:15:38  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13523', 'amount': '201'}
 Tue, 10 Mar 2020 15:15:38  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Tue, 10 Mar 2020 15:15:38  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '', 'amount': '201'}
 Tue, 10 Mar 2020 15:15:38  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 15:15:39  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': ''}
 Tue, 10 Mar 2020 15:15:39  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20115', 'data': None, 'msg': '请输入金额'}, 实际结果是：{'status': 0, 'code': '20115', 'data': None, 'msg': '请输入金额'},测试通过
 Tue, 10 Mar 2020 15:15:39  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '20.098'}
 Tue, 10 Mar 2020 15:15:39  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}, 实际结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'},测试通过
 Tue, 10 Mar 2020 15:15:39  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '-30'}
 Tue, 10 Mar 2020 15:15:39  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 15:15:40  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '1000000'}
 Tue, 10 Mar 2020 15:15:40  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 15:15:40  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '哈哈'}
 Tue, 10 Mar 2020 15:15:40  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}, 实际结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'},测试通过
 Tue, 10 Mar 2020 15:15:40  INFO test_recharge.py tearDownClass [ line:47 ] ==================== 充值接口测试接口测试执行完毕====================
 Tue, 10 Mar 2020 15:15:40  INFO test_register1.py setUpClass [ line:55 ] ==================== 准备开始执行注册接口测试 ====================
 Tue, 10 Mar 2020 15:15:40  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13378676037', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:41  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:41  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14991815984', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:41  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:41  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15366759133', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:41  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:41  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17375560805', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:41  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:42  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17769014621', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:42  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:42  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18003769283', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:42  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:42  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18128823196', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:42  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18967608369', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:43  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '19976669443', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:43  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13036127626', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:43  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13108782212', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:44  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:44  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13214636985', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:44  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:44  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14546761910', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:44  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:44  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15590808222', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:44  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:45  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15698533289', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:45  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:45  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '16638801897', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:45  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:45  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17173502394', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:45  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:46  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17556022954', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:46  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:46  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17603993743', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:46  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:46  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18514489754', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:46  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:47  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18636824316', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:47  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:47  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '16667210175', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:47  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:47  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13428743459', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:47  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13570941825', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 15:15:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13609483806', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 15:15:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13743271927', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 15:15:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13868351700', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 15:15:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13969552452', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 15:15:49  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14701340931', 'pwd': '1234567', 'regname': 'user4'}
 Tue, 10 Mar 2020 15:15:49  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15020726777', 'pwd': '1234567', 'regname': 'user4'}
 Tue, 10 Mar 2020 15:15:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:50  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15112423824', 'pwd': '1234567', 'regname': 'user5'}
 Tue, 10 Mar 2020 15:15:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:50  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15219772414', 'pwd': '1234567', 'regname': 'user5'}
 Tue, 10 Mar 2020 15:15:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:50  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15791733709', 'pwd': '1234567', 'regname': 'user6'}
 Tue, 10 Mar 2020 15:15:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:51  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15871387843', 'pwd': '1234567', 'regname': 'user6'}
 Tue, 10 Mar 2020 15:15:51  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:51  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15996371462', 'pwd': '1234567', 'regname': 'user7'}
 Tue, 10 Mar 2020 15:15:51  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:51  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17213556238', 'pwd': '1234567', 'regname': 'user7'}
 Tue, 10 Mar 2020 15:15:51  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17860350617', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 15:15:52  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18236152377', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 15:15:52  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18374476114', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 15:15:52  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18452751181', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 15:15:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:53  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18746839521', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 15:15:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:53  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18893076549', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 15:15:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:53  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18946277499', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 15:15:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 15:15:54  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '19212963864', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 15:15:54  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 15:15:54  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 15:15:54  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20110", "data":None, "msg":"手机号码已被注册"}, 实际结果是：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'},测试通过
 Tue, 10 Mar 2020 15:15:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 15:15:55  INFO test_register1.py test_register [ line:94 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 15:15:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13087138650', 'pwd': '', 'regname': 'user2'}
 Tue, 10 Mar 2020 15:15:55  ERROR test_register1.py test_register [ line:90 ] {'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
- {'code': '20103', 'data': None, 'msg': '手机号不能为空', 'status': 0}
?                                         ^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?                                         ^^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
- {'code': '20103', 'data': None, 'msg': '手机号不能为空', 'status': 0}
?                                         ^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?                                         ^^

 Tue, 10 Mar 2020 15:15:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18244503537', 'pwd': '123', 'regname': 'user3'}
 Tue, 10 Mar 2020 15:15:55  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20108", "data":None, "msg":"密码长度必须为6~18"}, 实际结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'},测试通过
 Tue, 10 Mar 2020 15:15:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '1389087', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 15:15:56  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20109", "data":None, "msg":"手机号码格式不正确"}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Tue, 10 Mar 2020 15:15:56  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18369677697', 'pwd': '哈哈', 'regname': 'user3'}
 Tue, 10 Mar 2020 15:15:56  ERROR test_register1.py test_register [ line:90 ] {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'} != {'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
- {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?               ^                         ^^^ ^^^^^

+ {'code': '20108', 'data': None, 'msg': '密码长度必须为6~18', 'status': 0}
?               ^                         ^ ^^^^^^^^^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'} != {'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
- {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?               ^                         ^^^ ^^^^^

+ {'code': '20108', 'data': None, 'msg': '密码长度必须为6~18', 'status': 0}
?               ^                         ^ ^^^^^^^^^

 Tue, 10 Mar 2020 15:15:56  INFO test_register1.py tearDownClass [ line:61 ] ==================== 注册接口测试执行完毕====================
 Tue, 10 Mar 2020 15:15:56  INFO test_withdraw.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Tue, 10 Mar 2020 15:15:56  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 15:15:56  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 15:15:57  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '32423', 'pwd': '1234568'}
 Tue, 10 Mar 2020 15:15:57  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 15:15:57  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 15:15:57  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 15:15:57  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'amount': '1'}
 Tue, 10 Mar 2020 15:15:58  ERROR test_withdraw.py test_login [ line:77 ] {'status': 1, 'code': '10001', 'data': {'id': 1507, [178 chars]现成功'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
- {'code': '10001',
-  'data': {'id': 1507,
-           'leaveamount': '7786.00',
-           'mobilephone': '13941387738',
-           'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759',
-           'regname': 'user1',
-           'regtime': '2020-03-09 14:25:05.0',
-           'type': '1'},
-  'msg': '取现成功',
-  'status': 1}
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_withdraw.py", line 74, in test_login
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': {'id': 1507, [178 chars]现成功'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
- {'code': '10001',
-  'data': {'id': 1507,
-           'leaveamount': '7786.00',
-           'mobilephone': '13941387738',
-           'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759',
-           'regname': 'user1',
-           'regtime': '2020-03-09 14:25:05.0',
-           'type': '1'},
-  'msg': '取现成功',
-  'status': 1}
 Tue, 10 Mar 2020 15:15:58  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '20.098'}
 Tue, 10 Mar 2020 15:15:58  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}, 实际结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'},测试通过
 Tue, 10 Mar 2020 15:15:58  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '-30'}
 Tue, 10 Mar 2020 15:15:58  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 15:15:58  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '哈哈'}
 Tue, 10 Mar 2020 15:15:58  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}, 实际结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'},测试通过
 Tue, 10 Mar 2020 15:15:59  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'amount': '5000000'}
 Tue, 10 Mar 2020 15:15:59  ERROR test_withdraw.py test_login [ line:77 ] {'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
- {'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
?              ^^                         ^^^^^^^^^^^^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?              ^^                         ^^^^^^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_withdraw.py", line 74, in test_login
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'} != {'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
- {'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额', 'status': 0}
?              ^^                         ^^^^^^^^^^^^^^^^^^

+ {'code': '20103', 'data': None, 'msg': '密码不能为空', 'status': 0}
?              ^^                         ^^^^^^

 Tue, 10 Mar 2020 15:15:59  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'amount': '#amout'}
 Tue, 10 Mar 2020 15:15:59  INFO test_withdraw.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
