 Mon, 09 Mar 2020 14:04:28  INFO test_login.py setUpClass [ line:39 ] ==================== 准备开始执行登录接口测试 ====================
 Mon, 09 Mar 2020 14:04:28  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '15815541732', 'pwd': '123456'}
 Mon, 09 Mar 2020 14:04:28  ERROR test_login.py test_login [ line:71 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'} != {'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
- {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?            ^^^                          ^^^^             ^

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
?           ++ ^                          ^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_login.py", line 68, in test_login
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'} != {'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
- {'code': '10001', 'data': None, 'msg': '登录成功', 'status': 1}
?            ^^^                          ^^^^             ^

+ {'code': '20111', 'data': None, 'msg': '用户名或密码错误', 'status': 0}
?           ++ ^                          ^^^^^^^^             ^

 Mon, 09 Mar 2020 14:04:28  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '150 71369970', 'pwd': '123456'}
 Mon, 09 Mar 2020 14:04:29  INFO test_login.py test_login [ line:75 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Mon, 09 Mar 2020 14:04:29  INFO test_login.py tearDownClass [ line:45 ] ==================== 登录接口测试执行完毕====================
 Mon, 09 Mar 2020 14:04:29  INFO test_recharge.py setUpClass [ line:41 ] ==================== 准备开始执行充值接口测试 ====================
 Mon, 09 Mar 2020 14:04:29  INFO test_recharge.py tearDownClass [ line:47 ] ==================== 充值接口测试接口测试执行完毕====================
 Mon, 09 Mar 2020 14:04:29  INFO test_register1.py setUpClass [ line:55 ] ==================== 准备开始执行注册接口测试 ====================
 Mon, 09 Mar 2020 14:04:29  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18337699345', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 14:04:29  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 14:04:29  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18542480134', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 14:04:29  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 14:04:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13967685539', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 14:04:30  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 14:04:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15815541733', 'pwd': '1234567', 'regname': 'user2'}
 Mon, 09 Mar 2020 14:04:30  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20110", "data":None, "msg":"手机号码已被注册"}, 实际结果是：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'},测试通过
 Mon, 09 Mar 2020 14:04:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18240584379', 'pwd': '123', 'regname': 'user3'}
 Mon, 09 Mar 2020 14:04:30  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20108", "data":None, "msg":"密码长度必须为6~18"}, 实际结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'},测试通过
 Mon, 09 Mar 2020 14:04:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '1389087', 'pwd': '1234567', 'regname': 'user3'}
 Mon, 09 Mar 2020 14:04:31  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20109", "data":None, "msg":"手机号码格式不正确"}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Mon, 09 Mar 2020 14:04:31  INFO test_register1.py tearDownClass [ line:61 ] ==================== 注册接口测试执行完毕====================
